# -*- coding: utf-8 -*-
"""
Created on 2016-12-28
@author hechangshu1
"""

var = {
    "table": "fx_orders",
    "fields": """CREATE TABLE "fx_orders"
        (
        "o_id" bigint(20) unsigned NOT NULL COMMENT "订单编号",
        "m_id" bigint(20) NOT NULL DEFAULT "0" COMMENT "会员ID",
        "m_name" varchar(50) NOT NULL DEFAULT "" COMMENT "会员名称",
        "m_mobile" varchar(20) NOT NULL DEFAULT "" COMMENT "会员手机",
        "m_telephone" varchar(20) NOT NULL DEFAULT "" COMMENT "会员固定电话",
        "m_real_name" varchar(25) NOT NULL DEFAULT "" COMMENT "会员姓名",
        "m_idcard" varchar(25) NOT NULL DEFAULT "" COMMENT "会员身份证号",
        "o_goods_total_price" decimal(10,4) NOT NULL DEFAULT "0.0000" COMMENT "订单商品单价总和",
        "o_total_price" decimal(10,4) NOT NULL DEFAULT "0.0000" COMMENT "订单总金额",
        "o_discount" decimal(10,4) NOT NULL DEFAULT "0.0000" COMMENT "订单优惠金额",
        "o_pay" decimal(10,4) NOT NULL DEFAULT "0.0000" COMMENT "已支付金额",
        "o_coupon" tinyint(1) NOT NULL DEFAULT "0" COMMENT "使用优惠劵 0.否，1.是",
        "c_sn" varchar(32) NOT NULL DEFAULT "" COMMENT "优惠券序列号",
        "o_coupon_menoy" decimal(10,4) NOT NULL DEFAULT "0.0000" COMMENT "订单使用优惠券金额",
        "o_cost_freight" decimal(10,4) NOT NULL DEFAULT "0.0000" COMMENT "订单物流费用",
        "o_payment" int(11) NOT NULL DEFAULT "0" COMMENT "主支付方式id",
        "o_payment_name" varchar(300) NOT NULL DEFAULT "" COMMENT "支付方式名称",
        "o_receiver_name" varchar(50) NOT NULL DEFAULT "" COMMENT "收货人",
        "o_receiver_mobile" varchar(15) NOT NULL DEFAULT "" COMMENT "收货人手机",
        "o_receiver_telphone" varchar(30) NOT NULL DEFAULT "" COMMENT "收货人电话",
        "o_receiver_province" varchar(50) NOT NULL DEFAULT "" COMMENT "省份",
        "o_receiver_city" varchar(50) NOT NULL DEFAULT "" COMMENT "收货人城市",
        "o_receiver_district" varchar(50) NOT NULL DEFAULT "" COMMENT "县区",
        "o_receiver_address" varchar(255) NOT NULL DEFAULT "" COMMENT "收货人地址",
        "cr_path" varchar(50) NOT NULL DEFAULT "" COMMENT "地址库路径",
        "o_receiver_zipcode" varchar(10) NOT NULL DEFAULT "" COMMENT "收货人邮编",
        "o_create_time" datetime NOT NULL DEFAULT "0000-00-00 00:00:00" COMMENT "订单创建时间",
        "o_update_time" datetime NOT NULL DEFAULT "0000-00-00 00:00:00" COMMENT "订单修改时间",
        "o_status" enum("WAIT_BUYER_PAY","PAYMENT_PROCESSING","SELLER_CONSIGNED_PART","WAIT_SELLER_SEND_GOODS","WAIT_BUYER_CONFIRM_GOODS","TRADE_FINISHED","TRADE_CLOSED","BUYER_PART_PAY","TRADE_CLOSED_BY_PLATFORM","ORDER_COMPLETED","WAIT_SEND_GOODS","WAIT_SELLER_PREPARE_GOODS","WAIT_BUYER_TAKE_DELIVERY","SELLER_CONSIGNED","CUSTOMER_SERVICE_PROCESSING") NOT NULL DEFAULT "WAIT_BUYER_PAY",
        "o_receiver_email" varchar(100) NOT NULL DEFAULT "" COMMENT "收货人邮箱",
        "lc_name" varchar(50) NOT NULL DEFAULT "" COMMENT "物流公司名称",
        "lc_id" int(11) NOT NULL DEFAULT "0" COMMENT "物流公司id",
        "lm_id" int(11) NOT NULL DEFAULT "0" COMMENT "配送方式id",
        "lm_name" varchar(50) NOT NULL DEFAULT "" COMMENT "配送方式名称",
        "o_audit" tinyint(1) NOT NULL DEFAULT "0" COMMENT "审核状态(0未审核,1审核)",
        "o_buyer_comments" varchar(500) NOT NULL DEFAULT "" COMMENT "买家留言",
        "o_seller_comments" varchar(500) NOT NULL DEFAULT "" COMMENT "卖家备注",
        "o_partform_comments" varchar(500) NOT NULL DEFAULT "" COMMENT "平台备注",
        "is_invoice" tinyint(1) NOT NULL DEFAULT "0" COMMENT "是否开发票 0:否 1:是 ",
        "po_id" bigint(20) NOT NULL DEFAULT "0" COMMENT "父订单号",
        "flag_type" tinyint(1) unsigned NOT NULL DEFAULT "0" COMMENT "订单旗帜(6个)",
        "o_after_status" enum("AGREE_NOT_EXIST","WAIT_REFUND_AGREE","REFUND_HAS_AGREED","WAIT_RETURN_AGREE","REFUND_SUCCESS","RETURN_SUCCESS","REFUND_CLOSED","RETURN_CLOSED","RETURN_HAS_AGREED","REFUND_PROCESSING","RETURN_PROCESSING") NOT NULL DEFAULT "AGREE_NOT_EXIST" COMMENT "售后状态 AGREE_NOT_EXIST没有售后 WAIT_REFUND_AGREE退款中 WAIT_RETURN_AGREE退货中 REFUND_SUCCESS退款成功 RETURN_SUCCESS退货成功 REFUND_CLOSED退款驳回 RETURN_CLOSED退货驳回 REFUND_HAS_AGREED卖家已同意退款，REFUND_PROCESSING：退款处理中，RETURN_PROCESSING：退货处理中",
        "shop_id" int(11) unsigned NOT NULL COMMENT "店铺ID",
        "shop_name" varchar(50) NOT NULL DEFAULT "" COMMENT "店铺名称",
        "o_pay_time" datetime NOT NULL DEFAULT "0000-00-00 00:00:00" COMMENT "订单支付时间",
        "o_notice_type" tinyint(1) NOT NULL DEFAULT "0" COMMENT "通知类型 0: 无通知 1:未成团通知 2:已成团通知",
        "o_completed_time" datetime NOT NULL DEFAULT "0000-00-00 00:00:00" COMMENT "订单完成时间",
        "o_closed_time" datetime NOT NULL DEFAULT "0000-00-00 00:00:00" COMMENT "订单关闭时间",
        "o_trade_succ_time" datetime NOT NULL DEFAULT "0000-00-00 00:00:00" COMMENT "交易成功时间，即确认收货时间",
        "o_logis_time" datetime NOT NULL COMMENT "发货时间",
        "o_delayed_time" datetime DEFAULT "0000-00-00 00:00:00" COMMENT "延迟自动确认收货时间",
        "o_source" varchar(20) NOT NULL DEFAULT "pc" COMMENT "订单来源(pc,phone_android,phone_ios)",
        "store_coupon" tinyint(1) NOT NULL DEFAULT "0" COMMENT "使用店铺优惠劵 0.否，1.是",
        "store_sn" varchar(32) NOT NULL DEFAULT "" COMMENT "店铺优惠卷",
        "store_coupon_money" decimal(10,4) NOT NULL DEFAULT "0.0000" COMMENT "订单使用店铺优惠券金额",
        "o_is_display" tinyint(1) NOT NULL DEFAULT "1" COMMENT "订单是否在订单列表显示：1显示，0不显示",
        "o_point_consume" int(11) NOT NULL DEFAULT "0" COMMENT "该订单分摊的消费的积分",
        "o_point_money" decimal(10,4) NOT NULL DEFAULT "0.0000" COMMENT "消费积分的对应金额",
        "is_notified" tinyint(1) NOT NULL DEFAULT "0" COMMENT "是否使用过提醒发货/催发货功能 0否 1是",
        "is_self_delivery" tinyint(1) NOT NULL DEFAULT "0" COMMENT "是否为自提订单 0否 1是",
        "o_auto_confirm_time" datetime DEFAULT NULL COMMENT "自动确认收货时间",
        "out_pay_no" varchar(64) DEFAULT "" COMMENT "对外交易编号",
        "point_add" decimal(10,4) DEFAULT NULL COMMENT "积了多少积分（订单总积分）",
        "coupon_batch_id" varchar(64) DEFAULT NULL COMMENT "使用券的批次ID",
        "coupon_batch_name" varchar(255) DEFAULT NULL COMMENT "使用券的批次名称",
        PRIMARY KEY ("o_id"),
        KEY "m_id" ("m_id") USING BTREE,
        KEY "o_receiver_name" ("o_receiver_name"(8)) USING BTREE,
        KEY "o_payment" ("o_payment") USING BTREE,
        KEY "o_receiver_mobile" ("o_receiver_mobile") USING BTREE,
        KEY "ra_path" ("cr_path") USING BTREE,
        KEY "o_create_time" ("o_create_time") USING BTREE,
        KEY "o_update_time" ("o_update_time") USING BTREE,
        KEY "o_status" ("o_status") USING BTREE,
        KEY "o_audit" ("o_audit") USING BTREE,
        KEY "po_id" ("po_id") USING BTREE,
        KEY "lc_id" ("lc_id") USING BTREE,
        KEY "o_after_status" ("o_after_status") USING BTREE,
        KEY "is_invoice" ("is_invoice") USING BTREE,
        KEY "o_coupon" ("o_coupon") USING BTREE,
        KEY "o_notice_type" ("o_notice_type") USING BTREE,
        KEY "o_completed_time" ("o_completed_time") USING BTREE,
        KEY "o_closed_time" ("o_closed_time") USING BTREE,
        KEY "o_trade_succ_time" ("o_trade_succ_time") USING BTREE,
        KEY "c_sn" ("c_sn") USING BTREE,
        KEY "shop_id" ("shop_id") USING BTREE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT="订单基本表";"""
}

